# Generated by Django 3.2 on 2021-05-01 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='image',
            field=models.ImageField(default='favicon.jpg', upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='thumbnail',
            field=models.ImageField(default='favicon.jpg', upload_to='uploads/'),
        ),
    ]
